### ISSUE TITLE
calc error with javascript

### ISSUE THREAD

**Issue by birdol** [psychrometrics/psychrolib#45] opened 2019-11-10 03:35 UTC
Download form github latest version 
```
var psychrolibSI = require('../../utils/psychrolib.js')
psychrolibSI.SetUnitSystem(psychrolibSI.SI)
var result= psychrolibSI.CalcPsychrometricsFromTWetBulb(20, 15, 101325);
console.log(result)
```
```
0:1e-7
1: -87.10730529927714
2: Infinity
3: 0.016291630885105456
4: 20120.25382
5: 57.43149724107621
6: 1
```

anything wrong with my code?

**Comment by dmey** [comment] 2019-11-10 10:09
Looks OK but just tried locally on Node.js v10.16.3 and could not reproduce the issue -- what version of Node.js and sys are you using? 

![image](https://user-images.githubusercontent.com/26348635/68542069-22b29100-03a0-11ea-9972-1275453c19b3.png)

**Comment by birdol** [comment] 2019-11-11 11:26
ok i got that error。i use var db = 20，ide make number to string，then... error happen

**Comment by dmey** [comment] 2019-11-11 11:39
Good. Will close this now.

**Closed by dmey** 2019-11-11 11:39 UTC
